name: Build PyInstaller Executables for Multiple Platforms

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当创建 PR 到 main 分支时触发

jobs:
  build:
    steps:
      - name: 执行文件点击打开获取ss节点信息
        run: ./ss
